#!/bin/bash

#for python tools
mkdir -p $HOME/.loki/apps/python

cp -r bin $HOME/.loki
cp .profile $HOME/.loki/

echo "" >> $HOME/.bash_profile
echo '. $HOME/.loki/.profile' >> $HOME/.bash_profile

. $HOME/.loki/.profile
